/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,ts,jsx,tsx}", "./components/**/*.{js,ts,jsx,tsx}", "./utils/**/*.{js,ts,jsx,tsx}"],
  plugins: [require("daisyui")],
  darkTheme: "dark",
  darkMode: ["selector", "[data-theme='dark']"],
  daisyui: {
    themes: [
      {
        light: {
          primary: "#E0C097",
          "primary-content": "#4D3B27",
          secondary: "#F7EFD8",
          "secondary-content": "#4D3B27",
          accent: "#D2B48C",
          "accent-content": "#4D3B27",
          neutral: "#4D3B27",
          "neutral-content": "#ffffff",
          "base-100": "#ffffff",
          "base-200": "#FDF8F0",
          "base-300": "#F5EBD9",
          "base-content": "#4D3B27",
          info: "#D2B48C",
          success: "#A0C4A6",
          warning: "#FFCF72",
          error: "#E8A088",
          "--rounded-btn": "9999rem",
          ".tooltip": { "--tooltip-tail": "6px" },
          ".link": { textUnderlineOffset: "2px" },
          ".link:hover": { opacity: "80%" },
        },
      },
      {
        dark: {
          primary: "#5A482C",
          "primary-content": "#FDF8F0",
          secondary: "#7D623A",
          "secondary-content": "#FDF8F0",
          accent: "#BF9F7F",
          "accent-content": "#FDF8F0",
          neutral: "#FDF8F0",
          "neutral-content": "#6B5336",
          "base-100": "#6B5336",
          "base-200": "#5A462D",
          "base-300": "#4D3B27",
          "base-content": "#FDF8F0",
          info: "#6B5336",
          success: "#A0C4A6",
          warning: "#FFCF72",
          error: "#E8A088",
          "--rounded-btn": "9999rem",
          ".tooltip": { "--tooltip-tail": "6px", "--tooltip-color": "oklch(var(--p))" },
          ".link": { textUnderlineOffset: "2px" },
          ".link:hover": { opacity: "80%" },
        },
      },
    ],
  },
  theme: {
    extend: {
      boxShadow: { center: "0 0 12px -2px rgb(0 0 0 / 0.05)" },
      animation: { "pulse-fast": "pulse 1s cubic-bezier(0.4, 0, 0.6, 1) infinite" },
    },
  },
};
